name: Build Raylib Game for Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..

    - name: Build
      run: |
        source emsdk/emsdk_env.sh
        make

    - name: Upload page artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
